#tuples
# languages=("Python","Java","C++")
# print(languages)
# print(type(languages))
# languages = ("Python", "Java", "C++")
# print(languages[2])
# languages = ("Python", "Java", "C++")
# print(languages[-1])
# languages = ("Python", "Java", "C++")
# print(languages[-3])
# languages=("Python", "Java", "C++")
# languages[1]="JavaScript"
# print(languages)
# languages = ("Python", "Java", "Python", "C++")
# print(languages.count("Python"))
# languages = ("Python", "Java", "C++")
# print(languages.index("C++"))
# languages = ("Python", "Java", "C++")
# language1,language2,language3=languages
# print(language1)
# print(language2)
# print(language3)