#tuples
# languages=("Python","Java","C++")
# print(languages)
# print(type(languages))
# languages = ("Python", "Java", "C++")
# print(languages[2])
# languages = ("Python", "Java", "C++")
# print(languages[-1])
# languages = ("Python", "Java", "C++")
# print(languages[-3])